cli = require 'cli'
[path, fs] = [cli.native.path, cli.native.fs]

exports.setup = ->
  unless properties.name
    cli.fatal "name must be set"
  else
    name = properties.name

  try
   sourcefile = fs.readFile "#{app_dir}/sources.json", (err, data) ->
    cli.fatal err if err
    if directory_exists("#{app_dir}/app/views/#{name}")
      cli.fatal "scene with that name already exists"
    source = JSON.parse(data)
    source.push
      scenes: name
      source: "app/assistants/#{name}-assistant.js"
    fs.writeFile "#{app_dir}/sources.json", JSON.stringify(source), (err) -> cli.error(err) if err

    fs.readFile path.join(mypath, "./templates/new_scene/assistant.coffee"), (err, data) ->
      cli.fatal(err) if err
      console.log typeof data
      data = String(data).replace("_NAME_", name)
      fs.writeFile "#{app_dir}/app/assistants/#{name}-assistant.coffee", data, (err) -> cli.error(err) if err

    fs.mkdir "#{app_dir}/app/views/#{name}", 0777, (err) ->
      cli.error err if err
      fs.writeFile "#{app_dir}/app/views/#{name}/#{name}-scene.html", "autogenerated", (err) ->
        cli.error err if err
  catch e
    cli.fatal e

